apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: gh-jenkins-artifactory-go-cwunsqdw 
  janus-idp.io/tekton: gh-jenkins-artifactory-go-cwunsqdw
  backstage.io/kubernetes-id: gh-jenkins-artifactory-go-cwunsqdw
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gh-jenkins-artifactory-go-cwunsqdw
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml